services:
  test:
    image: qa-practice.selenium
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: 
      - /bin/sh
      - -c 
      - |
       pytest -s --alluredir=allure-results
       allure generate --single-file allure-results --clean
       rm -rf allure-results
    working_dir: /usr/workspace
